# Generated by Django 5.2.4 on 2025-07-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, unique=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='Anonymous', max_length=100)),
                ('action', models.CharField(choices=[('add', 'Add'), ('complete', 'Complete'), ('delete', 'Delete')], default='N/A', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='text',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
