# Generated by Django 5.2.4 on 2025-07-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_history_alter_todoitem_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='completed',
        ),
        migrations.AlterField(
            model_name='history',
            name='action',
            field=models.CharField(max_length=50),
        ),
    ]
