# Generated by Django 5.2.4 on 2025-07-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_remove_history_completed_alter_history_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
